export default [
  {
    id: 1,
    name: 'Refining',
    active: false,
    color: '#AA5555',
    produces: 'Gems',
    producesId: 4,
    produceAmount: 1,
    actionTime: '5000',
    mcProficiency: 30,
    mcpTriggerAmount: 2000,
    triggered: false,
    mcpDiscoverAmount: 5000,
    discovered: false,
    decrements: 'Rocks',
    decrementAmount: 5,
    visible: false
  },
  {
    id: 2,
    name: 'Milling',
    active: false,
    color: '#423821',
    produces: 'Boards',
    producesId: 5,
    produceAmount: 1,
    actionTime: '10000',
    mcProficiency: 60,
    mcpTriggerAmount: 20000,
    triggered: false,
    mcpDiscoverAmount: 50000,
    discovered: false,
    decrements: 'Trees',
    decrementAmount: 3,
    visible: false
  },
  {
    id: 3,
    name: 'Cooking',
    active: false,
    color: '#be6868',
    produces: 'Cooked Fish',
    producesId: 6,
    produceAmount: 1,
    actionTime: '15000',
    mcProficiency: 100,
    mcpTriggerAmount: 200000,
    triggered: false,
    mcpDiscoverAmount: 500000,
    discovered: false,
    decrements: 'Fish',
    decrementAmount: 2,
    visible: false
  }
];
